# Generated by Django 5.2 on 2025-10-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ipay_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
