# Generated by Django 5.2 on 2025-10-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_ipay_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ipay_reference',
        ),
    ]
